<?php
/**
 * Project completion report: a professional, client-deliverable summary --
 * team, task completion, and project notes. Deliberately excludes every
 * credential/secret, since this is meant to be handed to people outside the
 * vault (print/Save-as-PDF, or copy as plain text).
 * Administrator/Manager only (whoever can manage this project's team).
 */
require_once __DIR__ . '/../includes/init.php';
requirePermission('tasks.manage');

$id = isset($_GET['id']) ? (int) $_GET['id'] : 0;

$stmt = $db->prepare('SELECT * FROM projects WHERE id = :id');
$stmt->execute(['id' => $id]);
$project = $stmt->fetch();

if (!$project) {
    flash('error', 'Project not found.');
    redirect(BASE_URL . '/projects/index.php');
}

if (!canAccessProject($id)) {
    require __DIR__ . '/../403.php';
    exit;
}

$members = $db->prepare(
    'SELECT pm.project_role, u.full_name, u.username
       FROM project_members pm JOIN users u ON u.id = pm.user_id
      WHERE pm.project_id = :pid
      ORDER BY pm.project_role, u.full_name'
);
$members->execute(['pid' => $id]);
$members = $members->fetchAll();

$tasks = $db->prepare(
    'SELECT t.title, t.status, t.due_date, u.full_name, u.username
       FROM project_tasks t LEFT JOIN users u ON u.id = t.assigned_to
      WHERE t.project_id = :pid
      ORDER BY FIELD(t.status, "done", "in_progress", "open"), t.due_date IS NULL, t.due_date'
);
$tasks->execute(['pid' => $id]);
$tasks = $tasks->fetchAll();
$doneCount = count(array_filter($tasks, static fn ($t) => $t['status'] === 'done'));

$comments = $db->prepare('SELECT author_name, body, created_at FROM project_comments WHERE project_id = :pid ORDER BY created_at ASC');
$comments->execute(['pid' => $id]);
$comments = $comments->fetchAll();

$generatedBy = currentUser()['full_name'] ?: currentUser()['username'];
$generatedAt = date('F j, Y \a\t g:i A');

// Plain-text rendition for the Copy button -- built once, server-side, so the
// button never has to reconstruct formatting in JavaScript.
$plain = "PROJECT COMPLETION REPORT\n";
$plain .= "{$project['name']}\n";
$plain .= str_repeat('=', strlen($project['name'])) . "\n\n";
if ($project['category']) { $plain .= "Category: {$project['category']}\n"; }
if ($project['description']) { $plain .= "Description: {$project['description']}\n"; }
$plain .= "Generated by {$generatedBy} on {$generatedAt}\n\n";

$plain .= "TEAM\n----\n";
foreach ($members as $m) {
    $plain .= '- ' . ($m['full_name'] ?: $m['username']) . ' (' . ($m['project_role'] === 'manager' ? 'Manager' : 'Tester') . ")\n";
}
if (!$members) { $plain .= "(none assigned)\n"; }

$plain .= "\nTASKS (" . $doneCount . '/' . count($tasks) . " completed)\n" . str_repeat('-', 20) . "\n";
foreach ($tasks as $t) {
    $mark = $t['status'] === 'done' ? '[x]' : '[ ]';
    $assignee = $t['full_name'] ?: $t['username'] ?: 'Unassigned';
    $due = $t['due_date'] ? ' (due ' . date('M j, Y', strtotime($t['due_date'])) . ')' : '';
    $plain .= "$mark {$t['title']} -- $assignee$due\n";
}
if (!$tasks) { $plain .= "(no tasks recorded)\n"; }

if ($comments) {
    $plain .= "\nPROJECT NOTES\n-------------\n";
    foreach ($comments as $c) {
        $plain .= '[' . date('M j, Y', strtotime($c['created_at'])) . "] {$c['author_name']}: {$c['body']}\n";
    }
}

$pageTitle = 'Report: ' . $project['name'];
$activePage = 'projects';

require __DIR__ . '/../includes/header.php';
?>

<div class="card no-print">
    <div class="card__header">
        <h2 class="card__title">Project Report</h2>
        <div class="quick-actions quick-actions--row">
            <a class="btn btn--small" href="view.php?id=<?= (int) $id ?>">&larr; Back to project</a>
            <button type="button" class="btn btn--small" id="copy-report-btn">📋 Copy as text</button>
            <button type="button" class="btn btn--small btn--primary" onclick="window.print()">🖨 Print / Save as PDF</button>
        </div>
    </div>
    <p class="muted" style="margin-top:-8px">Contains no passwords or credentials -- safe to share outside the vault.</p>
</div>

<textarea id="report-plain-text" hidden readonly><?= e($plain) ?></textarea>

<div class="card report">
    <div class="report__letterhead">
        <div class="report__brand"><?= navIcon('lock') ?> <?= e(appName()) ?></div>
        <div class="report__meta">Generated by <?= e($generatedBy) ?> on <?= e($generatedAt) ?></div>
    </div>

    <h1 class="report__title"><?= $project['category'] ? e(projectCategoryIcon($project['category'])) : '📁' ?> <?= e($project['name']) ?></h1>
    <?php if ($project['category']): ?><p><span class="badge badge--role"><?= e($project['category']) ?></span></p><?php endif; ?>
    <?php if ($project['description']): ?><p><?= nl2br(e($project['description'])) ?></p><?php endif; ?>

    <h2 class="report__section">Team</h2>
    <?php if ($members): ?>
        <table class="table">
            <thead><tr><th>Name</th><th>Role</th></tr></thead>
            <tbody>
            <?php foreach ($members as $m): ?>
                <tr>
                    <td><?= e($m['full_name'] ?: $m['username']) ?></td>
                    <td><?= $m['project_role'] === 'manager' ? 'Manager' : 'Tester' ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <p class="muted">No team members assigned.</p>
    <?php endif; ?>

    <h2 class="report__section">Tasks <span class="muted" style="font-weight:400">(<?= $doneCount ?>/<?= count($tasks) ?> completed)</span></h2>
    <?php if ($tasks): ?>
        <table class="table">
            <thead><tr><th></th><th>Task</th><th>Assigned To</th><th>Status</th><th>Due</th></tr></thead>
            <tbody>
            <?php foreach ($tasks as $t): ?>
                <tr>
                    <td><?= $t['status'] === 'done' ? '✅' : '⬜' ?></td>
                    <td><?= e($t['title']) ?></td>
                    <td><?= e($t['full_name'] ?: $t['username'] ?: 'Unassigned') ?></td>
                    <td><?= e(taskStatusOptions()[$t['status']]) ?></td>
                    <td><?= $t['due_date'] ? e(date('M j, Y', strtotime($t['due_date']))) : '—' ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <p class="muted">No tasks recorded.</p>
    <?php endif; ?>

    <?php if ($comments): ?>
        <h2 class="report__section">Project Notes</h2>
        <?= renderProjectComments($comments) ?>
    <?php endif; ?>
</div>

<script>
    document.getElementById('copy-report-btn').addEventListener('click', function () {
        var text = document.getElementById('report-plain-text').value;
        var btn = this;
        navigator.clipboard.writeText(text).then(function () {
            var original = btn.textContent;
            btn.textContent = 'Copied!';
            setTimeout(function () { btn.textContent = original; }, 1500);
        });
    });
</script>

<?php require __DIR__ . '/../includes/footer.php'; ?>
